### ISSUE TITLE
The parsing seems stale and no events are showing

### ISSUE THREAD

**Issue by yangchenyun** [jrejaud/sfcityguidescalendar#1]

**Comment by jrejaud** [comment]
Since the data is screen scrapped from the SF city guides website, I think that website changed its HTML code, I'll look over it and see if I can resolve the issue, sorry for the troubles.

**Comment by jrejaud** [comment]
Hi @yangchenyun, I think I fixed it. Thanks for the feedback :)

**Comment by yangchenyun** [comment]
👍 👍
